[[plugins]]
repo = 'neoclide/coc.nvim'
on_ft = ['python']
merged = 0
rev = 'release'
hook_source = '''
" navigate diagnostics
nmap <silent> [g <Plug>(coc-diagnostic-prev)
nmap <silent> ]g <Plug>(coc-diagnostic-next)

" Go to navigation
nmap <silent> <C-]> <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

nnoremap <silent> K :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction
'''

[[plugins]]
repo = 'skanehira/preview-markdown.vim'
hook_add = '''
  let g:preview_markdown_vertical = 1
  let g:preview_markdown_auto_update = 1
'''
